kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3
        imagePullPolicy: IfNotPresent
        name: rabbitmq
        ports:
        - containerPort: 5672
          name: amqp
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          value: "mycookie"
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - persistentVolumeClaim: 
          claimName: rabbitmq-data
        name: rabbitmq-data
