apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: default
  name: rabbitmq-data
spec:
  storageClassName: openebs-standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
